name: Daily connectivity update

on:
  schedule:
    # 06:05 UTC ~= 03:05 Chile (UTC-3). Ajusta si quieres otra hora.
    - cron: "5 6 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run-update:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install pandas numpy requests openpyxl python-dateutil; fi

      - name: Run daily pipeline (download + compute + snapshot)
        env:
          COPILOTO_EMAIL: ${{ secrets.COPILOTO_EMAIL }}
          COPILOTO_PASSWORD: ${{ secrets.COPILOTO_PASSWORD }}
          COPILOTO_TOKEN: ${{ secrets.COPILOTO_TOKEN }}
          COPILOTO_SIGNIN_URL: ${{ secrets.COPILOTO_SIGNIN_URL }}
        run: |
          python pipeline_daily.py

      - name: Commit updated data files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --staged --quiet || git commit -m "Daily update: connectivity data"
          git push
